linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - revive
    - gosec
    - misspell
    - unconvert
    - unparam
    - nakedret
    - gocritic

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
    enable-all: true
  
  revive:
    confidence: 0.8
  
  gosec:
    severity: medium
    confidence: medium
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-use-default: false
  max-same-issues: 0

run:
  timeout: 5m
  go: '1.25'
